version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: talkify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre@123
    ports:
      - "5432:5432"